---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-lb-service
spec:
  ports:
  - port: 80 # LoadBalancer IP Port to access
    # nodePort: 30001 #No need to assign as its gets assigned randomly
    # targetPort: vproapp-port #port of the pod 
    targetPort: 8090
    protocol: TCP
  selector:
    app: vpro
  type : LoadBalancer