---
apiVersion: v1
kind: Pod
metadata:
  name : sample-secret-pod
spec: 
  containers:
  - name: redisContainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-sample-secret
            key: username
            optional: false

      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-sample-secret
            key: password
            optional: false